### ISSUE TITLE
Cannot disable input dynamically with disable prop

### ISSUE THREAD

**Issue by frederikhors** [jacobmischka/svelte-flatpickr#21]
Hi @jacobmischka! Thanks for you great work on this project!

I found a strange thing, **REPL**: https://svelte.dev/repl/e112a7119f2041fcbe8c5237f2f6138a?version=3.24.1.

It doesn't disable input if I change the `disabled` at runtime.

If I change the code to `let disabled = true` the input is disabled and then I cannot change it anymore with the button click.

Is this something wrong with me? :smile:

**Comment by jacobmischka** [comment]
I think this is actually the same problem as https://github.com/haoxins/react-flatpickr/issues/125: the `disabled` prop applies to the underlying input element, not the flatpickr component. I think you should use one of the flatpickr options instead of toggling `disabled` directly.

Let me know if this doesn't make sense.

**Comment by frederikhors** [comment]
Oh wow. I think it works now: https://svelte.dev/repl/e112a7119f2041fcbe8c5237f2f6138a.

Crazy things! 🤣

**Comment by jacobmischka** [comment]
Sick! Must have been an underlying flatpickr issue that was addressed. I'm going to close this in that case. Thanks for writing back!
