### ISSUE TITLE
What do you think about making flatpickr peer dep?

### ISSUE THREAD

**Issue by frederikhors** [jacobmischka/svelte-flatpickr#43]
What do you think about making flatpickr peer dep?

**Comment by jacobmischka** [comment]
I don't think it's necessary, semantic versioning should be enough, `npm upgrade` should always give you the latest one since we don't provide a maximum version (until 5.0 is released, if ever). The only reason to would be if people wanted to use older versions of it, which I don't see the reason for.

**Comment by jacobmischka** [comment]
If you want to lock the dependency you can add it to your own dependencies and that's the one that your package manager should give you, or you can use a package manager with specific `resolutions` like yarn.
