### ISSUE TITLE
Demo sapper implementation

### ISSUE THREAD

**Issue by orenrobi** [jacobmischka/svelte-flatpickr#6]
Hi @jacobmischka, new to svelte and I'm trying to make an [example Sapper repo](https://github.com/orenrobi/demo-sapper-svelte-flatpickr) using this datepicker, and running into build issues.

I've used an [example webpack config for sapper](https://gist.github.com/MaxMilton/80cf8330b29876c1241d4ed345412f27) for my [webpack.config.js](https://github.com/orenrobi/demo-sapper-svelte-flatpickr/blob/master/webpack.config.js), and the example code from the README in this repo in my [routes/index.html](https://github.com/orenrobi/demo-sapper-svelte-flatpickr/blob/master/src/routes/index.html).

I'm currently getting this CSS loader error. Any pointers?

![screenshot from 2018-12-25 20-07-45](https://user-images.githubusercontent.com/31669069/50432049-27ec1780-0884-11e9-8a20-a63670b971cb.png)

**Comment by jacobmischka** [comment]
Hi! Server rendering with Sapper fails when it tries to load css files, because by default no css loaders are specified in the webpack config. You can handle that in a variety of ways, but I tend to use `ignore-loader`. Here's the `webpack.config.js` of one of my projects: https://gist.github.com/jacobmischka/f36b6a635d924d610c212164aac296ff

Please feel free to write back if you run into any other issues.
